spring:
  application:
    name: syscode-demo
  datasource:
    url: jdbc:h2:~/h2/syscode-db;DB_CLOSE_ON_EXIT=true
    username: sa
    password: admin
    hikari:
      auto-commit: false
  liquibase:
    change-log: ./config/liquibase/master.xml
    password: admin
  jpa:
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
    hibernate.ddl-auto: update
logging:
  level:
    org: error
app:
  address-service:
    api:
      url: http://localhost:8081/address